<?php
/*
 * This file is part of Litotex | Open Source Browsergame Engine.
 *
 * Litotex is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Litotex is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Litotex.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * This package is like a dashboard, so a lot of information is generated by hooks
 * @FIXME Almost everything
 * @author Jonas Schwabe <jonas.schwabe@gmail.com>
 * @hooks None (yet)
 */
class package_main extends package{
	/**
	 * Name of the module, please do not change this!
	 * @var string
	 */
    protected $_packageName = 'main';
    /**
     * No dependencies because they are loaded automatic by hook's
     * @var array
     */
    public static $dependency = array('core_buildings');
    protected $_availableActions = array('main');
	public function __action_main(){
		return true;
	}
	public static function registerHooks(){
		return true;
	}
}
